### ISSUE TITLE
Driver issues

### ISSUE THREAD

**Issue by Waxes27** [Daemitrious/9anime_dl#6]
Grabbing available episodes...
Traceback (most recent call last):
  File "/home/waxes27/9anime_dl/__main__.py", line 85, in <module>
    eps = list(grabeps(driver()))
  File "/home/waxes27/9anime_dl/relative.py", line 81, in driver
    return Firefox(options=headless(Options()), service_log_path="/home/pi/Documents/Programming/Data/Logs/9anime_dl.txt")
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 160, in __init__
    self.service = Service(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/service.py", line 44, in __init__
    log_file = open(log_path, "a+") if log_path is not None and log_path != "" else None
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/Documents/Programming/Data/Logs/9anime_dl.txt'

**Comment by Waxes27** [comment]
Would be nice to have the driver already within the repo before hand and the code refers to the driver instead of having the user to setup their own

**Comment by Daemitrious** [comment]
@Waxes27 fixed the logging path and i made it so that it automatically grabs the latest and compatible version from the mozilla geckodriver repo
